### ISSUE TITLE
Name cannot be resolved.

### ISSUE THREAD

**Issue by ejgeiger** [ejgeiger/imon#1]
I changed the ping to google.com (deleted the www.) and will monitor.

Sep 20 09:13:34 raspberrypi imon[10780]: Exception in thread Thread-1:
Sep 20 09:13:34 raspberrypi imon[10780]: Traceback (most recent call last):
Sep 20 09:13:34 raspberrypi imon[10780]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/utils.py", line 108, in resolve
Sep 20 09:13:34 raspberrypi imon[10780]:     lookup = socket.getaddrinfo(
Sep 20 09:13:34 raspberrypi imon[10780]:   File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
Sep 20 09:13:34 raspberrypi imon[10780]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Sep 20 09:13:34 raspberrypi imon[10780]: socket.gaierror: [Errno -3] Temporary failure in name resolution
Sep 20 09:13:34 raspberrypi imon[10780]: During handling of the above exception, another exception occurred:
Sep 20 09:13:34 raspberrypi imon[10780]: Traceback (most recent call last):
Sep 20 09:13:34 raspberrypi imon[10780]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Sep 20 09:13:34 raspberrypi imon[10780]:     self.run()
Sep 20 09:13:34 raspberrypi imon[10780]:   File "/usr/local/bin/imon", line 314, in run
Sep 20 09:13:34 raspberrypi imon[10780]:     host = ping(self.pd.db['updown']['monitorip'], count=self.pd.db['updown']['pingcount'], timeout=self.pd.db['updown']['pingwait'], privileged=True)
Sep 20 09:13:34 raspberrypi imon[10780]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/ping.py", line 130, in ping
Sep 20 09:13:34 raspberrypi imon[10780]:     address = resolve(address, family)[0]
Sep 20 09:13:34 raspberrypi imon[10780]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/utils.py", line 118, in resolve
Sep 20 09:13:34 raspberrypi imon[10780]:     return resolve(name, 6)
Sep 20 09:13:34 raspberrypi imon[10780]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/utils.py", line 120, in resolve
Sep 20 09:13:34 raspberrypi imon[10780]:     raise NameLookupError(name)
Sep 20 09:13:34 raspberrypi imon[10780]: icmplib.exceptions.NameLookupError: The name 'www.google.com' cannot be resolved

**Comment by ejgeiger** [comment]
Still getting this error after changing the ping:

Sep 21 13:21:41 raspberrypi imon: imon [berkeley] Monitored IP 4.2.2.2 offline
Sep 21 13:21:41 raspberrypi root: imon action [berkeley] updown-offline: updown-offline 4.2.2.2 
Sep 21 13:21:50 raspberrypi imon[1768]: Exception in thread Thread-1:
Sep 21 13:21:50 raspberrypi imon[1768]: Traceback (most recent call last):
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/utils.py", line 158, in async_resolve
Sep 21 13:21:50 raspberrypi imon[1768]:     lookup = await loop.getaddrinfo(
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
Sep 21 13:21:50 raspberrypi imon[1768]:     return await self.run_in_executor(
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Sep 21 13:21:50 raspberrypi imon[1768]:     result = self.fn(*self.args, **self.kwargs)
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
Sep 21 13:21:50 raspberrypi imon[1768]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Sep 21 13:21:50 raspberrypi imon[1768]: socket.gaierror: [Errno -3] Temporary failure in name resolution
Sep 21 13:21:50 raspberrypi imon[1768]: During handling of the above exception, another exception occurred:
Sep 21 13:21:50 raspberrypi imon[1768]: Traceback (most recent call last):
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Sep 21 13:21:50 raspberrypi imon[1768]:     self.run()
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/local/bin/imon", line 326, in run
Sep 21 13:21:50 raspberrypi imon[1768]:     self._reportdown()
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/local/bin/imon", line 308, in _reportdown
Sep 21 13:21:50 raspberrypi imon[1768]:     self._ckmonitoredips()
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/local/bin/imon", line 284, in _ckmonitoredips
Sep 21 13:21:50 raspberrypi imon[1768]:     hosts = multiping(addresses=self.pd.db['updown']['addping'], count=self.pd.db['updown']['pingcount'], timeout=self.pd.db['updown']['pingwait'], privileged=True)
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/multiping.py", line 267, in multiping
Sep 21 13:21:50 raspberrypi imon[1768]:     return asyncio.run(
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Sep 21 13:21:50 raspberrypi imon[1768]:     return loop.run_until_complete(main)
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Sep 21 13:21:50 raspberrypi imon[1768]:     return future.result()
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/multiping.py", line 163, in async_multiping
Sep 21 13:21:50 raspberrypi imon[1768]:     return [task.result() for task in tasks]
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/multiping.py", line 163, in <listcomp>
Sep 21 13:21:50 raspberrypi imon[1768]:     return [task.result() for task in tasks]
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/ping.py", line 263, in async_ping
Sep 21 13:21:50 raspberrypi imon[1768]:     address = (await async_resolve(address, family))[0]
Sep 21 13:21:50 raspberrypi imon[1768]:   File "/usr/local/lib/python3.9/dist-packages/icmplib/utils.py", line 168, in async_resolve
Sep 21 13:21:50 raspberrypi imon[1768]:     return await async_resolve(name, 6)
Sep 21 13:21:50 raspberrypi imon[1768]: icmplib.exceptions.NameLookupError: The name 'thrivehere.com' cannot be resolved
